# Generated by Django 5.0.6 on 2025-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBot', '0003_chatmesage_session_id_alter_chatmesage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmesage',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='chatmesage',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
